name: 'Publish to S3'
description: 'Publish artifacts to S3 bucket'
inputs:
  aws_secret_access_key:
    description: AWS secret access key
    required: true
  aws_access_key:
    description: AWS access key
    required: true
  aws_s3_bucket_name:
    description: Name of the S3 bucket
    required: true
  repo_name:
    description: Combination of organization and repository (i.e. newrelic/nri-redis)
    required: true
  app_name:
    description: Name of the package (i.e. nri-redis)
    required: true
  tag:
    description: Tag pointing to the release
    required: true
  schema:
    description: Name of the schema describing the packages to be published (i.e. infra-agent, ohi, nrjmx, custom - requires schemaUrl)
    required: true
  schema_url:
    description: Url to custom schema file
    required: false
  env:
    description: Type of environment (release, pre-release)
    required: true
  gpg_passphrase:
    description: Passphrase for the gpg key
    required: false
  gpg_private_key_base64:
    description: Encoded gpg key
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action-run.sh
      shell: bash
      env:
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_ACCESS_KEY: ${{ inputs.aws_access_key }}
        AWS_S3_BUCKET_NAME: ${{ inputs.aws_s3_bucket_name }}
        GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
        GPG_PRIVATE_KEY_BASE64: ${{ inputs.gpg_private_key_base64}}
        REPO_NAME: ${{ inputs.repo_name }}
        APP_NAME: ${{ inputs.app_name }}
        TAG: ${{ inputs.tag }}
        ENV: ${{ inputs.env }}
        SCHEMA: ${{ inputs.schema }}
        SCHEMA_URL: ${{ inputs.schema_url }}
