#!/bin/bash
set -e

# All parameters from the action come as env vars with the format INPUT_<NAME OF INPUT>
# Ex: aws_region -> INPUT_AWS_REGION

# declare non-configurable env vars
WORKDIR=/home/gha
AWS_S3_MOUNT_DIRECTORY=/mnt/s3
ARTIFACTS_SRC_FOLDER=$WORKDIR/assets
ARTIFACTS_DEST_FOLDER=$AWS_S3_MOUNT_DIRECTORY

# automate this
GPG_PRIVATE_KEY_BASE64=$INPUT_GPG_PRIVATE_KEY_BASE64
GPG_KEY_RING=$INPUT_GPG_KEY_RING
GPG_PASSPHRASE=$INPUT_GPG_PASSPHRASE
AWS_SECRET_ACCESS_KEY=$INPUT_GPG_PASSPHRASE
AWS_ACCESS_KEY_ID=$INPUT_AWS_ACCESS_KEY_ID
AWS_S3_BUCKET_NAME=$INPUT_AWS_S3_BUCKET_NAME 
AWS_ROLE_ARN=$INPUT_AWS_ROLE_ARN

# check env vars
export

# run the makefile
make --jobs=1
