---
name: UnitTesting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: Validate code
        run: make validate

      - name: Running unit tests
        run: make test